repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: cef0300fd0fc4d2a87a85fa2093c6b283ea36f4b  # frozen: v5.0.0
  hooks:
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: check-toml

- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 84080c769d17e250eb32ac0d10662c7bf03ad346  # frozen: 0.31.3
  hooks:
    - id: check-dependabot
    - id: check-github-workflows
      args: ["--verbose"]

- repo: https://github.com/asottile/reorder-python-imports
  rev: fd0b4e1292716bcd12a396b86af1d1271aaaa62c  # frozen: v3.14.0
  hooks:
    - id: reorder-python-imports

- repo: git@github.com:brokenpip3/pre-commit-hooks
  rev: 2e66d2cdfa400781b92d6a5cd165d45130105dc6
  hooks:
    - id: github-actions-hash
      files: ^.github/workflows/.*\.(yml|yaml)$ # limit only to github workflows

- repo: local
  hooks:
  - id: pytest-check
    name: pytest-check
    types: [python]
    files: ^src/
    entry: pytest -v -s .
    language: system
    pass_filenames: false

  - id: ruff-format
    name: ruff-format
    types: [python]
    files: ^src/
    entry: ruff format
    language: system
    pass_filenames: false

  - id: ruff-check
    name: ruff-check
    types: [python]
    files: ^src/
    entry: ruff check --fix
    language: system
    pass_filenames: false
